apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
  resourceVersion: "2180"
  selfLink: /api/v1/namespaces/default/secrets/db-secret
  uid: e8f7acf9-4e7d-4d9c-8092-77f9cc570240
type: Opaque
data:
  DB_Host: c3FsMDE=
  DB_Password: cGFzc3dvcmQxMjM=
  DB_User: cm9vdA==
